WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/gspread/client.py", line 168, in open_by_key
    spreadsheet = Spreadsheet(self.http_client, {"id": key})
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/gspread/spreadsheet.py", line 29, in __init__
    metadata = self.fetch_sheet_metadata()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/gspread/spreadsheet.py", line 230, in fetch_sheet_metadata
    return self.client.fetch_sheet_metadata(self.id, params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/gspread/http_client.py", line 305, in fetch_sheet_metadata
    r = self.request("get", url, params=params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/gspread/http_client.py", line 128, in request
    raise APIError(response)
gspread.exceptions.APIError: APIError: [403]: Request had insufficient authentication scopes.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/main.py", line 53, in <module>
    main(
  File "/app/main.py", line 30, in main
    workbook = gspread.authorize(cred).open_by_url(url)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/gspread/client.py", line 189, in open_by_url
    return self.open_by_key(extract_id_from_url(url))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/gspread/client.py", line 173, in open_by_key
    raise PermissionError from ex
PermissionError
WRAPPER> Shutdown handler called
WRAPPER> No process is running
